-- 0002_seed_cartas.sql — GENERADO (roja: cartas.csv, verde: db/verdes.csv)
-- Re-generar con: bun scripts/gen-cartas.mjs
insert into public.cartas (color, tipo, texto, flavor) values
  ('roja', 'Personajes', 'El Pollo Brito', 'El hombre que es capaz de meterle un solo de cuatro y un "¡Epa!" a cualquier canción del mundo, incluyendo el reguetón más oscuro o una de Metallica.'),
  ('roja', 'Personajes', 'Nagueboná, Vladimir', 'El reclamo viral que repetimos sin saber bien por qué'),
  ('roja', 'Personajes', 'Miguel Cabrera', 'Un señor que batea pelotazos a 400 pies de distancia en el imperio pero que celebra los triunfos con un flow de malandro de Maracay'),
  ('roja', 'Personajes', 'El Gocho', 'El ser más trabajador, amable y respetuoso del país, hasta que maneja un camión de verduras bajando la autopista a 120 km/h sin frenos.'),
  ('roja', 'Personajes', 'El Valenciano', 'Ciudadano de la capital del "Epa, pana". Se rumorea que nacen con una camisa de marca y un odio natural hacia los caraqueños.'),
  ('roja', 'Personajes', 'El Caraqueño', 'Alguien que cree que después de los túneles de Tazón todo lo demás es "monte y culebra", aunque sufre tres horas de cola para comprar pan.'),
  ('roja', 'Personajes', 'El Oriental', 'Todo es ''a la orden, vale''; vive entre playa, pesca y relax'),
  ('roja', 'Personajes', 'El Maracucho', 'El único ser humano capaz de usar el "¡Qué molleja!" como sustantivo, verbo, adjetivo y declaración de guerra, todo bajo un calor de 42°C.'),
  ('roja', 'Personajes', 'Maite Delgado', 'El estándar de elegancia nacional. Si ella no dice "¡Buenas noches, Poliedro!", el evento simplemente no cuenta.'),
  ('roja', 'Personajes', 'Deyna Castellanos', 'La mujer que demostró que en Venezuela el fútbol también se juega con clase, tacos y goles de media cancha que dejan a los hombres llorando.'),
  ('roja', 'Personajes', 'El bachaquero de la esquina', 'Un economista empírico que no estudió en Harvard, pero te calcula el cambio del dólar flotante, paralelo y del futuro en tres segundos.'),
  ('roja', 'Espanto', 'El Silbón', 'Un gigantón con complejo de músico frustrado que carga un saco de huesos. Si lo escuchas lejos, corre a rezar; si lo escuchas cerca... bueno, ya no importa.'),
  ('roja', 'Espanto', 'La Sayona', 'La pesadilla de los hombres infieles.'),
  ('roja', 'Espanto', 'La Loca Luz Caraballo', 'El personaje andino que perdió la cuenta de los hijos y la cordura. La excusa perfecta que usan tus amigos cuando andas buscando algo y no lo encuentras.'),
  ('roja', 'Personajes', 'El Doctor Knoche', 'El mismísimo Dr. Frankenstein del Ávila.'),
  ('roja', 'Personajes', 'Ánima del Purgatorio', 'A la que le prenden una vela para que cuide el carro o ayude a pasar el examen. Eso sí, si le quedas mal, te jala las patas a medianoche.'),
  ('roja', 'Dichos', '"Quedar como novia de pueblo"', 'El estado máximo de la decepción. Vestido, alborotado y esperando en la plaza por algo que obviamente nunca iba a llegar.'),
  ('roja', 'Dichos', '"Ponerse las alpargatas"', 'El aviso oficial de que la situación se puso color de hormiga. Porque lo que viene no es joropo, es rock pesado.'),
  ('roja', 'Dichos', '"Echarle Bolas"', 'El acto heroico de trabajar duro contra todo pronóstico, la luz, el agua y CANTV, con una sonrisa en la cara.'),
  ('roja', 'Dichos', '"Más perdido que el hijo de Lindbergh"', '¿El hijo de quien?'),
  ('roja', 'Dichos', '"Matar un tigre"', 'El arte de la supervivencia económica. Hacer tres trabajos extra que no tienen nada que ver con tu profesión para poder llegar a la quincena.'),
  ('roja', 'Comida', 'Un perro caliente "Con Todo" a las 3:00 a.m.', 'Una obra de arte de la ingeniería callejera que desafía las leyes de la gravedad y de la digestión. Lleva repollo, papitas y 14 salsas misteriosas.'),
  ('roja', 'Comida', 'La empanada "Operada"', 'Una empanada normal a la que abren a la mitad sin piedad para meterle queso, carne, tajada y todo lo que quepa. Ingeniería pura.'),
  ('roja', 'Comida', 'Queso guayanés derretido', 'El único material en el universo capaz de estirarse desde la mesa hasta la boca de tu vecino sin romperse.'),
  ('roja', 'Comida', 'Una arepa de "Dominó"', 'La combinación perfecta de caraotas negras y queso blanco. Deliciosa para el paladar, peligrosa para los que duermen contigo esa noche.'),
  ('roja', 'Comida', 'El "Pegao" de la olla de arroz', 'El oro crujiente del fondo de la olla por el cual los hermanos menores están dispuestos a batirse a duelo con cucharas de palo.'),
  ('roja', 'Musica', 'Mercedes', 'El cuento de la vaca que se metió en el caño por floja y el caimán la agarró. La metáfora venezolana perfecta para el que se busca sus propios problemas.'),
  ('roja', 'Musica', 'Venezuela', 'El himno sentimental que hace llorar instantáneamente a cualquier venezolano que esté a más de 50 kilómetros de la frontera.'),
  ('roja', 'Musica', 'El Alma Llanera', 'La señal internacional de que la fiesta SE ACABÓ. Si suena esto, recoge tus cosas, busca tus zapatos y vete, porque van a prender las luces blancas.'),
  ('roja', 'Musica', '1 y 1 es igual a 3', 'El himno oficial del infiel arrepentido que intenta usar matemáticas creativas para explicar por qué lo vieron con otra en el centro comercial.'),
  ('roja', 'Musica', 'Llorarás', 'La canción que te hace bailar salsa aunque tengas dos pies izquierdos y estés sufriendo por un amor que te dejó limpio.'),
  ('roja', 'Musica', 'El "Cumpleaños Feliz"', 'La tortura psicológica de 15 minutos donde te cantan cuatro canciones distintas, te meten el "ay, qué noche tan preciosa" y terminas con dolor de aplaudir.'),
  ('roja', 'Guachafitas', '"Al fondo hay puesto"', 'La mentira más grande del transporte público. El "fondo" no existe, es una dimensión desconocida donde la gente viaja flotando.'),
  ('roja', 'Guachafitas', 'Un "bajón" de luz justo cuando vas a guardar la tesis', 'El microinfarto nacional. El momento exacto donde ves la pantalla negra y recuerdas que no habías apretado "Control + G" desde 2023.'),
  ('roja', 'Personajes', 'La tía que te manda cadenas de Piolín por WhatsApp', 'Tu dosis diaria de "Bendiciones, sobrino" acompañada de un GIF brillante que pesa 45 megabytes y te colapsa la memoria del teléfono.'),
  ('roja', 'Guachafitas', 'El "Vuelto" en caramelos', 'La moneda de curso legal impuesta por los comercios. Nadie sabe cuántos mentados de menta equivalen a un dólar, pero todos los aceptamos.'),
  ('roja', 'Guachafitas', 'Un chisme en el trabajo', 'Información clasificada que corre más rápido que la fibra óptica de Cantv y que muta tres veces antes de llegar a la oficina del jefe.'),
  ('roja', 'Guachafitas', 'Quedarse sin agua a mitad del baño', 'El drama trágico caribeño. El instante en que descubres que el tanque falló y te toca buscar el tobito con los ojos cerrados.'),
  ('roja', 'Guachafitas', 'El pana que dice "Voy saliendo"', 'El manejo de la física cuántica del tiempo. Su "voy saliendo" significa que llegará en dos horas y probablemente oliendo a jabón recién usado.'),
  ('roja', 'Guachafitas', 'Juego de dominó un domingo por la tarde', 'Un deporte extremo donde se habla de política, se toma cerveza, se grita y se tranca la cochina con violencia dramática sobre la mesa.'),
  ('roja', 'Guachafitas', 'Motorizado esquivando la lluvia bajo un puente', 'Una convención espontánea de 40 personas con impermeables que trancan la autopista mientras esperan que pase la nube.'),
  ('roja', 'Guachafitas', 'El olor a tierra mojada cuando empieza mayo', 'La señal de la naturaleza de que preparen los tobos porque se viene el invierno (y las goteras del techo).'),
  ('roja', 'Personajes', 'La "Chola" de tu mamá', 'El único proyectil teledirigido del mundo que dobla las esquinas de la casa para impactar con precisión milimétrica en tu cabeza.'),
  ('roja', 'Evento', 'Un Caracas-Magallanes', 'El evento que divide familias, destruye noviazgos y paraliza al país por el simple placer de decirle al otro "llorón".'),
  ('roja', 'Personajes', 'El señor que vende helados en la playa', 'Un atleta de alto rendimiento que camina 15 kilómetros sobre la arena caliente cargando un cajón de anime mientras grita sin micrófono.'),
  ('roja', 'Guachafitas', '"Háblame, chamo"', 'El saludo universal que puede significar desde un cordial "buenos días" hasta un "estás en problemas y necesito que me expliques".'),
  ('roja', 'Objetos', 'Carro con los amortiguadores vencidos', 'Un vehículo que parece una licuadora andante y te hace sentir cada piedrita de la carretera directo en los riñones.'),
  ('roja', 'Guachafitas', 'El "Toque de queda" de la abuela', 'Las 9:00 p.m. Después de esa hora, si no estás en la casa, asume que estás en las noticias o que ya no formas parte de la familia.'),
  ('roja', 'Personajes', 'Lila Morillo', 'El verdadero misterio de la ciencia venezolana. Se rumorea que tiene el secreto de la eterna juventud y que sobrevivirá al fin del mundo junto a los coquitos.'),
  ('roja', 'Personajes', 'Er Conde del Guácharo', 'El embajador honorario de la "mamadera de gallo". Capaz de hacerte reír y ofenderte al mismo tiempo con una sola palabra de cuatro letras.'),
  ('roja', 'Personajes', 'Oscar D''León', 'El hombre que tiene más energía a las 3:00 a.m. que cualquier joven de 20 años después de tres cafés. ¡Sabroooso!'),
  ('roja', 'Comida', 'Una empanada de cazón en la playa', 'Manjar de los dioses que sabe mejor si viene acompañada de salsa de ajo, un chorrito de limón y moscas apuradas por probarla.'),
  ('roja', 'Comida', 'Una empanada de queso en la playa', 'Chamo, ¿de verdad?'),
  ('roja', 'Comida', 'La última papa frita del plato', 'El motivo real por el cual se han terminado grandes amistades y matrimonios en este país. Se mira, pero no se toca sin permiso.'),
  ('roja', 'Comida', 'Un Toddy bien frío', 'El abrazo en un vaso que cura el mal de amor, el cansancio y cualquier crisis existencial. Dejar los grumos arriba es ley.'),
  ('roja', 'Comida', 'Pirulín', 'La moneda de cambio emocional más valiosa del mercado. Si te regalan uno de los grandes, es amor verdadero.'),
  ('roja', 'Objetos', 'Un autobús con la música a todo volumen', 'Una discoteca móvil con olor a gasoil donde el chofer cree que está compitiendo en la Fórmula 1 y es el DJ al mismo tiempo.'),
  ('roja', 'Evento', 'La cola de la gasolina', 'El club social interactivo más grande del país. Donde juegas dominó, haces amigos para toda la vida y replanteas tu futuro a las 4:00 a.m.'),
  ('roja', 'Objetos', 'La calor Maracucha', 'Un fenómeno termodinámico que te hace sentir que estás caminando directamente sobre la superficie del sol, pero con un cepillao en la mano.'),
  ('roja', 'Evento', 'Bajón de luz', 'El enemigo silencioso que te hace saltar de la cama a las 2:00 a.m. a desenchufar la nevera como si fueras un experto en desactivar bombas.'),
  ('roja', 'Guachafitas', 'El "Te lo dije" de tu Mamá', 'La frase más temida, precisa y científicamente comprobada de la historia. Tiene un 100% de efectividad y duele más que un chancletazo.'),
  ('roja', 'Guachafitas', 'El "Ahorita"', 'Unidad de tiempo indeterminada que puede significar: en 5 minutos, en 3 horas, el próximo mes o, más probablemente, NUNCA.'),
  ('roja', 'Personajes', 'La sifrina', 'Habla con una papa en la boca y sufre si el lugar no tiene aire acondicionado. Jura que es de la realeza, pero se le va la luz igual que a ti.'),
  ('roja', 'Personajes', '"Malandro" de cartón', 'Camina de lado, habla grueso y dice que domina la zona, pero cuando escucha un triquitraqui sale corriendo a esconderse detrás de su mamá.'),
  ('roja', 'Personajes', 'Sugar daddy', 'Un señor con canas y billetera gorda cuyo único superpoder real es pasar la tarjeta de crédito sin mirar el monto en el punto de venta.'),
  ('roja', 'Personajes', 'La tía evangélica y chismosa', 'Te dice que vas directo al infierno por tus tatuajes y tus salidas los viernes, pero se sabe la vida íntima de todos los vecinos de la cuadra.'),
  ('roja', 'Personajes', 'El pana que se cree influencer', 'Graba historias mostrando los músculos en el gimnasio, tiene 200 seguidores y le pide prestado al papá para pagar la cuenta.'),
  ('roja', 'Personajes', 'La bendecida y afortunada', 'Modelo de redes sociales que viaja a playas exóticas "trabajando duro". Su mayor esfuerzo laboral es posar al lado de un señor de 70 años.'),
  ('roja', 'Personajes', 'Maracucho picado', 'Un volcán andante de groserías regionales. Capaz de insultar a tus ancestros solo porque le dijiste que en su ciudad hace mucho calor.'),
  ('roja', 'Personajes', 'Gocho despechado', 'El peligro hecho ternura. Se toma una botella de licor artesanal, llora con música llanera y llama a la ex a las 3:00 a.m. para pedirle perdón cantadito.'),
  ('roja', 'Personajes', 'La arrecha de barrio', 'El ser más peligroso del planeta si le quitan el puesto en la cola. Te arma un escándalo que incluye desprendimiento de uñas y pérdida de dignidad.'),
  ('roja', 'Personajes', 'El sabelotodo de la familia', 'Ese tío que opina de política, medicina, mecánica y física cuántica con la misma seguridad con la que se toma el tercer ron de la tarde.'),
  ('roja', 'Personajes', 'Amigo de lo ajeno', 'Ese personaje que te pide un cigarro, un trago o una empanada y termina consumiéndose la mitad de tus provisiones con toda la frescura del mundo.'),
  ('roja', 'Personajes', 'El vecino fastidioso del condominio', 'El que pasa el día vigilando quién deja la basura fuera de lugar o quién hace ruido a las 8:01 p.m. para poner la queja en el grupo de WhatsApp.'),
  ('roja', 'Personajes', 'La que no rompe un plato', 'Cara de ángel que va a misa los domingos, pero en las fiestas se toma hasta el agua de los floreros y se besa con tres amigos en la misma noche.'),
  ('roja', 'Personajes', 'La tóxica', 'Tu ex revisando tus historias de Instagram desde un perfil creado hace cinco minutos con la foto de un perrito tierno.'),
  ('roja', 'Personajes', 'El duende que te esconde las llaves', 'Un ser maligno que habita en todas las casas. Hace que las llaves desaparezcan y luego aparezcan mágicamente en el mismo lugar donde ya buscaste diez veces.'),
  ('roja', 'Dichos', '"Gastar pólvora en zamuro"', 'El acto inútil de intentar enamorar a esa persona que sabes perfectamente que se escribe con medio planeta y no te va a parar ni media bola.'),
  ('roja', 'Dichos', '"Chivo que se devuelve se esnuca"', 'La ley de oro de la mala junta. Si ya dijiste que te ibas a tomar la última fría, te la tomas; arrepentirse a última hora es de cobardes.'),
  ('roja', 'Dichos', '"Morder el peine"', 'Caer redondito en la trampa de tu pareja cuando te pregunta de forma inocente: "Mi amor, ¿quién es esa persona que te dio ''me gusta''?"'),
  ('roja', 'Guachafitas', 'Sacar el culo', 'El arte de la evasión cuando ves venir de lejos al conocido fastidioso que siempre te pide dinero prestado o quiere que le hagas un favor gratis.'),
  ('roja', 'Objetos', 'El "rompe colchón"', 'Un cóctel de mariscos que promete propiedades afrodisíacas milagrosas, pero que por lo general solo te garantiza pasar tres días metido en el baño.'),
  ('roja', 'Objetos', 'La salsita de ajo sospechosa del carrito callejero', 'Tiene tres días fuera de la nevera bajo el sol, pero le da ese sabor adictivo que te hace volver a pesar del riesgo de tifoidea.'),
  ('roja', 'Objetos', 'Anís con yogurt de fresa', 'La bebida oficial de las plazas públicas. Una mezcla satánica que sabe a jarabe para la tos pero te borra la memoria en media hora.'),
  ('roja', 'Objetos', 'Una chicha con exceso de leche condensada', 'Un cemento estomacal tan denso y dulce que te drena la energía y te obliga a dormir una siesta de cinco horas.'),
  ('roja', 'Objetos', 'Sopa de mondongo con pata de vaca', 'Un caldo espeso capaz de revivir a un muerto por resaca o de matar a un vivo por indigestión fulminante.'),
  ('roja', 'Objetos', 'El guayoyo amargo de oficina', 'Un café que parece agua de paraguas, hecho con la colada del día anterior, que solo sirve para mantenerte alterado y con acidez.'),
  ('roja', 'Objetos', 'Vallenato cortavenas a las 4:00 a.m.', 'El detonante definitivo para que los hombres barbudos empiecen a llorar, abracen a sus amigos y llamen a la ex diciendo "te extraño".'),
  ('roja', 'Personajes', 'Sandy y Papo', 'La música que despierta los instintos de baile prohibidos en cualquier tía de más de 50 años en medio de la sala, "Eh Eh, es hora de bailar".'),
  ('roja', 'Objetos', 'Reguetón viejo (2006)', 'Ese que saca tu lado más alegre y te hace olvidar por completo que tienes un título universitario y dos diplomados.'),
  ('roja', 'Objetos', 'La hora loca', 'El momento exacto donde la elegancia de la fiesta se va al demonio y el cumpleañero termina gateando con una corbata amarrada en la frente.'),
  ('roja', 'Objetos', 'Salsa brava', 'Música que te hace bailar en una "baldoza" y te da una excusa para abrazar a tu pareja de turno.'),
  ('roja', 'Objetos', 'El "visto" azul de WhatsApp', 'Esos diez minutos de silencio sepulcral donde revisas si todavía tienes pulso mientras esperas a ver si te mandan a lavarte ese culo.'),
  ('roja', 'Guachafitas', 'Tarjeta rechazada por fondos insuficientes', 'El momento más humillante de la existencia humana. Deseas que la tierra se abra y te trague junto con el código 51.'),
  ('roja', 'Evento', 'Quedarse sin papel tualé en baño ajeno', 'El drama existencial donde revisas desesperadamente el basurero, el rollo vacío y terminas sacrificando una media.'),
  ('roja', 'Evento', 'Ir a un motel y encontrarte un conocido', 'Una situación de alta tensión donde ambos se miran a través del parabrisas y firman un pacto implícito de silencio absoluto.'),
  ('roja', 'Personajes', 'El mecánico', 'Un cirujano automotriz que le cambia un tornillo a tu carro, te habla con términos inventados y te deja limpio por los próximos tres meses.'),
  ('roja', 'Personajes', 'La reunión de condominio', 'El evento anual donde los vecinos decentes se transforman en gladiadores romanos por culpa de una filtración o de una mascota inquieta.'),
  ('roja', 'Personajes', 'El conocido que te invita a "ser tu propio jefe"', 'Un estafador piramidal con traje alquilado que te cita en un café para explicarte cómo ganar millones vendiendo batidos o monedas virtuales.'),
  ('roja', 'Evento', 'Revisar el teléfono de tu pareja mientras se baña', 'Un deporte extremo no apto para cardíacos. Sabes que el que busca encuentra, pero igual ahí estás tú intentando adivinar la clave.'),
  ('roja', 'Evento', 'Hacerse el dormido en el autobús para no dar el puesto', 'Un acto de bajeza moral donde ensayas tu mejor cara de coma profundo mientras sientes la mirada juzgadora de todo el colectivo.'),
  ('roja', 'Objetos', 'Un piropo de albañil con exceso de creatividad', 'Una construcción poética callejera tan explícita y ordinaria que te hace dudar de si te están halagando o te están amenazando.'),
  ('roja', 'Personajes', 'El pana que se vuelve insoportable con dos tragos', 'Pasa de ser un tipo tranquilo a querer pelear con el mesonero, romper un vaso y confesarle su amor a la novia de su mejor amigo.'),
  ('roja', 'Personajes', 'El parquero de la calle', 'Un guía que solo aparece cuando vas a arrancar para pedirte una colaboración por haber visto cómo chocabas contra el poste.'),
  ('roja', 'Evento', '"A la derecha ciudadano"', 'El momento donde sudas frío, te acuerdas de todos tus pecados y rezas para que no se den cuenta de que tienes el documento vencido.'),
  ('roja', 'Evento', 'Comer caraotas tres días seguidos', 'Una decisión gastronómica deliciosa que se convierte en una bomba de tiempo si tienes una reunión en una oficina pequeña con aire acondicionado.'),
  ('roja', 'Objetos', 'La rumba en el estacionamiento de una licorería', 'Abrir la maleta del carro, poner la música a todo volumen, tomar de un vaso plástico y creerse el dueño del mundo hasta que llega la patrulla.'),
  ('roja', 'Objetos', 'Un tatuaje barato hecho en una sala', 'Una obra de arte que se suponía era un león imponente y terminó pareciendo un gato desnutrido con mala actitud.'),
  ('roja', 'Objetos', 'Mudanza hecha en el techo de un carro pequeño', 'Amarrar una nevera, una lavadora y dos colchones con un solo mecate y subir la autopista rezándole a todos los santos.'),
  ('roja', 'Objetos', 'El pre-despacho antes de ir a la discoteca', 'Tomarse media botella de ron barato en la sala de tu casa para no gastar adentro, y llegar tan borracho que el portero no te deja entrar.'),
  ('roja', 'Evento', 'Ya te hice la transferencia, debe estar por caer', 'La estafa digital más usada para ganar unas horas de paz con el cobrador mientras consigues el dinero de verdad.'),
  ('roja', 'Personajes', 'El gordito del grupo que siempre tiene calor', 'Un pana que suda como tapa de olla de presión a los dos minutos de apagar el aire acondicionado y te suplica que prendas el ventilador.'),
  ('roja', 'Objetos', 'Un dolor de barriga repentino en plena calle', 'La verdadera prueba de fe. Cuando tienes que usar todo tu control mental y espiritual para no pasar una vergüenza histórica en la avenida.'),
  ('roja', 'Evento', 'Ir a la playa y que llueva a los cinco minutos', 'La salazón astronómica que arruina el viaje, te moja las empanadas y te obliga a regresarte lleno de arena y frustración.'),
  ('roja', 'Objetos', 'El último trago', 'Ese vaso misterioso que te tomas a las 5:00 a.m. y te hace prometerle a Dios que más nunca vuelves a tocar el alcohol.'),
  ('roja', 'Personajes', 'Eladio Lárez', 'El caballero de la televisión. Un señor tan elegante y correcto que juras que duerme en traje y que te mira con decepción si fallas una pregunta tonta. "¿Estás seguro?"'),
  ('roja', 'Personajes', 'Valentina Quintero', 'La mujer que ha dormido en todas las posadas y ha comido empanada en todas las carreteras del mapa. si dice que un rancho con piso de tierra es "espectacular", tú vas con los ojos cerrados.'),
  ('roja', 'Personajes', 'Osmel Sousa', 'El hombre que destruyó la autoestima de tres generaciones de mujeres con solo mirarlas de arriba a abajo.'),
  ('roja', 'Personajes', 'Gilberto Correa', 'La voz oficial de las borracheras elegantes del Poliedro. El señor tenía tanta clase que podía anunciar que venía el fin del mundo y tú aplaudías pensando que era una atracción internacional de Sábado Sensacional.'),
  ('roja', 'Personajes', 'Renny Ottolina', 'El fantasma al que todos invocan cuando quieren decir que "antes todo era mejor".'),
  ('roja', 'Personajes', 'Daniel Sarcos', 'El animador que basó toda su carrera en correr por el escenario, abrazar señoras mayores de la emoción y gritar "¡Guerra de los sexos!" a todo pulmón.'),
  ('roja', 'Personajes', 'Viviana Gibelli', 'La mujer que perfeccionó el arte de fingir demencia en televisión en vivo mientras lidiaba con hombres intensos, concursos absurdos de meter las manos en urnas con cucarachas y coreografías baratas.'),
  ('roja', 'Personajes', 'Mimí Lazo', 'La mujer que facturó millones enseñándole a las mujeres despechadas del país que la culpa de su infelicidad siempre es de un hombre sin oficio.'),
  ('roja', 'Personajes', 'Norkys Batista', 'Una mujer con un cuerpo espectacular pero con una boca que parece un callejón sin salida a las 3:00 a.m.'),
  ('roja', 'Personajes', 'Edgar Ramírez', 'El chamo que logró el milagro de salir de las novelas baratas de la tarde venezolana para terminar actuando con Robert De Niro.'),
  ('roja', 'Personajes', 'La mujer de Judas', 'El juego de terror psicológico más grande de la televisión. Tenías a seis viejas millonarias vestidas de novia matando gente a diestra y siniestra.'),
  ('roja', 'Personajes', 'Mi gorda bella', 'Agarraron a una actriz espectacular, la metieron en un traje de goma que parecía un muñeco de Michelin, y nos querían convencer de que nadie se daba cuenta del truco.'),
  ('roja', 'Personajes', 'Voltea pa'' que te enamores', 'La novela que convenció a las sifrinas de que era buena idea salir con el mecánico o el mototaxista de la esquina porque "el amor todo lo puede". Un peligro para la economía familiar.'),
  ('roja', 'Personajes', 'Yulimar Rojas', 'Una chama de dos metros que salta tan lejos que viola las leyes de la física y de la gravedad, mientras celebra rompiendo récords mundiales bailando salsa brava frente a los europeos estiraos.'),
  ('roja', 'Personajes', 'Salomón Rondón', 'El "Gladiador". Un tanque humano cuya única estrategia es chocar contra defensas uruguayos o brasileños como si fuera una buseta sin frenos bajando por la autopista Caracas-La Guaira.'),
  ('roja', 'Personajes', 'Juan Arango', 'El hombre que tenía un pacto con el diablo en la pierna izquierda.'),
  ('roja', 'Personajes', 'Greivis Vásquez', 'El chamo que llegó a la NBA metiendo puro "chalequeo" caribeño.'),
  ('roja', 'Personajes', 'Bob Abreu', '"El Comedulce". Un tipo tan relajado para jugar que parecía que estaba jugando béisbol en la playa con una cerveza en la mano, pero igual te metía un jonrón y te robaba la base en tus narices.'),
  ('roja', 'Personajes', 'Rubén Limardo', 'El carajito que se fue a Londres con una espada a ganarse una medalla de oro en esgrima (un deporte que en Venezuela solo se practica cuando te van a atracar con un cuchillo).'),
  ('roja', 'Personajes', 'Pastor Maldonado', 'El piloto de Fórmula 1 que convirtió las carreras de autos en un juego de carritos chocones de feria. Sabías que el chamo corría rápido, pero la apuesta real en el país era ver en qué vuelta se iba a estrellar.'),
  ('roja', 'Personajes', 'Simón Díaz', 'El único hombre capaz de cantarle a una vaca enferma o a un caballo viejo y hacer que un malandro de discoteca se ponga a llorar de la nostalgia en plena borrachera.'),
  ('roja', 'Personajes', 'Emilio Lovera', 'El hombre que tiene secuestradas todas las voces del país. Si Emilio Lovera se muere, nos quedamos sin el 90% de los personajes cómicos, locutores de radio y borrachos icónicos de la cultura pop.'),
  ('roja', 'Personajes', 'Ricardo Montaner', 'El cantautor que vive en una secta familiar gigante en Miami donde todos cantan, todos se visten igual y todos le dan las gracias a Dios por las regalías de las canciones de telenovela de los 90.'),
  ('roja', 'Personajes', 'Gustavo Dudamel', 'El director de orquesta que mueve las manos como si estuviera espantando un enjambre de avispas africanas mientras los sifrinos de Europa lo aplauden pensando que está interpretando a Beethoven con pasión caribeña.'),
  ('roja', 'Personajes', 'Dayana Mendoza', 'Una mujer tan absurdamente bella que hacía que las demás candidatas del Miss Universo parecieran las primas feas que invitas a la fiesta por obligación. Su nivel de perfección roza la ilegalidad.'),
  ('roja', 'Personajes', 'José Luis Rodríguez', 'El hombre del copete indestructible que se cambió de religión, cambió de familia y ahora vive en Miami dándole consejos espirituales a la gente.'),
  ('roja', 'Personajes', 'Servando y Florentino', 'Los hermanos que causaron que la mitad de las adolescentes de los 90 perdieran la virginidad mental (y real) en un concierto.'),
  ('roja', 'Personajes', 'Winston Vallenilla', 'El animador que vendió su alma al canal del Estado a cambio de poder gritar "¡Familiaaa!"'),
  ('roja', 'Personajes', 'Luis Chataing', 'Su negocio era burlarse de los políticos en la mañana para que la gente atrapada en la cola de la autopista se riera en vez de pegarse un tiro.'),
  ('roja', 'Personajes', 'Juan Gabriel en el Teresa Carreño', 'Un mexicano cantando despechos mientras los hombres más machistas del país lloraban abrazados tomando whisky de 18 años.'),
  ('roja', 'Personajes', 'Chino y Nacho', 'Dos chamos que empezaron cantando reguetón ordinario en las discotecas de Caracas y terminaron ganando Grammys en Miami'),
  ('roja', 'Personajes', 'Reinaldo Armas', 'El cantante de música llanera que tiene el récord nacional de haber musicalizado la mayor cantidad de borracheras con caña clara.'),
  ('roja', 'Personajes', 'La Vinotinto de las Eliminatorias', 'Una secta masoquista nacional basada en la frase "Mano, tengo fe".'),
  ('roja', 'Personajes', 'Leones del Caracas', 'Los fanáticos más insoportables del béisbol caribeño.'),
  ('roja', 'Personajes', 'Navegantes del Magallanes', 'La mitad del país que se viste de pavo real cada vez que le ganan un juego a Caracas.'),
  ('roja', 'Personajes', 'Roque Valero', 'El cantautor de los sifrinos despechados que pasó de cantar baladas lloronas en RCTV a ganarse un puesto en la asamblea política del gobierno por puro amor al presupuesto nacional.'),
  ('roja', 'Personajes', 'Jeremías', 'El cantante flojo que sacó un solo disco exitoso, inventó una teoría matemática absurda para justificar la infidelidad'),
  ('roja', 'Personajes', 'Hany Kauam', 'El cantautor con pinta de indigente chic que musicalizó todos los despechos de bachillerato en el 2007.'),
  ('roja', 'Personajes', 'Antonio Ledezma', '"¡SE ESTÁN LLEVANDO A LEDEZMA! ¡SE ESTÁN LLEVANDO A LEDEZMA!".'),
  ('roja', 'Personajes', 'Juan Guaidó', 'El presidente interino de Narnia.'),
  ('roja', 'Otros', 'Henrique Capriles', 'El eterno perdedor con gorra tricolor.'),
  ('roja', 'Otros', 'Diosdi', 'Si hablas paja, te va a tocar calarte el calabozo.'),
  ('roja', 'Otros', 'Chiave', 'Nadie sabe bien quién es, pero todos lo nombran'),
  ('roja', 'Otros', 'El Bigoton', 'Famoso por hablar con pajaritos que reencarnan'),
  ('verde', 'Jerga', 'Arrecho', 'Buenísimo o bravísimo, según el día'),
  ('verde', 'Jerga', 'Chévere', 'Sello criollo de aprobación'),
  ('verde', 'Jerga', 'Chimbo', 'De pacotilla, pues'),
  ('verde', 'Jerga', 'Pavoso', 'Trae la sal pegada'),
  ('verde', 'Jerga', 'Ladilla', 'Fastidioso de oficio'),
  ('verde', 'Jerga', 'Sifrino', 'Fresa con acento gringo'),
  ('verde', 'Jerga', 'Rascado', 'Más prendido que un bombillo'),
  ('verde', 'Jerga', 'Tieso', 'Sin un medio... o sin moverse'),
  ('verde', 'Jerga', 'Burda de bueno', 'Demasiado, del bueno'),
  ('verde', 'Jerga', 'Jalabola', 'Adulador profesional'),
  ('verde', 'Jerga', 'Echao pa'' lante', 'No se arruga'),
  ('verde', 'Jerga', 'Pelando bola', 'Sin plata y sin oficio'),
  ('verde', 'Jerga', 'Camburao', 'Acomodado por palanca'),
  ('verde', 'Jerga', 'Enratonado', 'El día después de la juma'),
  ('verde', 'Jerga', 'Fino', 'Todo en orden, pana'),
  ('verde', 'Jerga', 'Mamador de gallo', 'Vive echando broma'),
  ('verde', 'Jerga', 'Bochinchero', 'Arma el peo donde llega'),
  ('verde', 'Jerga', 'Aguevoneado', 'Despistado nivel experto'),
  ('verde', 'Jerga', 'Sabroso', 'Rico, como debe ser'),
  ('verde', 'Jerga', 'Cuaima', 'Celosa con doctorado'),
  ('verde', 'Jerga', 'Arrechísimo', 'Arrecho al cubo'),
  ('verde', 'Jerga', 'Chimbísimo', 'Lo peor de lo peor'),
  ('verde', 'Jerga', 'Heavy', 'Pesado y fuerte'),
  ('verde', 'Jerga', 'Maluco', 'Tirando a feo'),
  ('verde', 'Jerga', 'Bravo', 'Molesto y con razón'),
  ('verde', 'Jerga', 'Picado', 'Resentido, pero disimula'),
  ('verde', 'Jerga', 'Templao', 'Enamorado hasta los tuétanos'),
  ('verde', 'Jerga', 'Flechao', 'Cupido le dio sin piedad'),
  ('verde', 'Jerga', 'Mosca', 'No le pasan gato por liebre'),
  ('verde', 'Jerga', 'Avispao', 'Vivo, pilas, despierto'),
  ('verde', 'Jerga', 'Brutal', 'Tan bueno que asusta'),
  ('verde', 'Jerga', 'Pelúo', 'Difícil, complicado'),
  ('verde', 'Jerga', 'Enrollao', 'Hecho un lío'),
  ('verde', 'Jerga', 'Embarrao', 'Metido en tremendo peo'),
  ('verde', 'Jerga', 'Salao', 'La mala suerte lo persigue'),
  ('verde', 'Jerga', 'Echón', 'Presumido sin razón'),
  ('verde', 'Jerga', 'Fanfarrón', 'Habla más de lo que hace'),
  ('verde', 'Jerga', 'Tripeao', 'Disfrutando a millón'),
  ('verde', 'Jerga', 'Mamao', 'Cansado, no puede más'),
  ('verde', 'Jerga', 'Fundío', 'Acabado, rendido'),
  ('verde', 'Jerga', 'Quedao', 'Lento hasta para el amor'),
  ('verde', 'Jerga', 'Cuadrao', 'Cerrado de mente'),
  ('verde', 'Jerga', 'Pesao', 'Antipático de nacimiento'),
  ('verde', 'Jerga', 'Misio', 'Sin un centavo'),
  ('verde', 'Jerga', 'Tóxico', 'Mejor lejos'),
  ('verde', 'Jerga', 'Intenso', 'Demasiado, siempre'),
  ('verde', 'Jerga', 'Zumbao', 'Loco de bola'),
  ('verde', 'Jerga', 'Despelucao', 'Recién levantado'),
  ('verde', 'Jerga', 'Fiebrúo', 'Obsesionado con su vaina'),
  ('verde', 'Jerga', 'Guapetón', 'Se las da de valiente')
on conflict (color, texto) do update
  set tipo = excluded.tipo, flavor = excluded.flavor, activa = true;
